### ISSUE TITLE
Chinese UI support

### ISSUE THREAD

**Issue by crispgm** [crispgm/UrlAutoRedirector#32]
- [x] Chinese Translations @lzb 
- [x] I18N Implementation @crispgm

**Comment by lzb** [comment]
any link to the translation page?

**Comment by lzb** [comment]
跳转设置（general=全局设置？）

在新的标签页中跳转
在当前标签页中跳转

规则
名字，源地址，目标地址，正则表达式

关于
版权所有 
……
本软件创意由 Albert Li 提供

**Comment by crispgm** [comment]
In my original design, General means 通用设置 @lzb
